make formats configurable
bnjjj/twelf pull request #13
Opened 2022-03-21 10:08 UTC by cking

due to project reasons i cant use AGPL licenses.
`serde_dhall` depends indirectly on `abnf` which is AGPL licensed.

the introduced features make it confgurable which loaders will be enabled

2022-03-21 13:00 UTC, bnjjj commented
Thanks ! It looks good ! Will take a look and try to use it to make some checks. I will release this today ! If I forgot feel free to ping me again tomorrow !

2022-03-21 13:54 UTC, bnjjj requested changes
It won't work because you have to use config attribute at the compile time, not directly into the generated code. I wrote examples here in this PR, you just need to do the same for other features https://github.com/cking/twelf/pull/1

2022-03-21 13:54 UTC, bnjjj commented on twelf/Cargo.toml
> +    default = ["envy", "dhall", "clap", "ini", "json", "yaml", "toml"]
```suggestion
    default = ["env", "dhall", "clap", "ini", "json", "yaml", "toml"]
```

2022-03-23 11:14 UTC, cking commented
i updated the code and made sure the examples work fine without throwing.

2022-03-23 11:19 UTC, cking commented
seems like something is still wrong in my project, let me investigate

2022-03-23 11:35 UTC, cking commented
and done - im not using serde_json so i did see an error it being always required

my project no compiles and runs completly again

thanks for your patience

2022-03-25 11:14 UTC, bnjjj commented
It looks good ! Thanks ! I will make a release ASAP

2022-03-25 11:14 UTC, bnjjj approved these changes

2022-03-25 11:14 UTC, merged

2022-03-25 11:42 UTC, bnjjj commented
Published on `0.3.0` cc @ThibsG it could be interesting for you in order to improve compile time